sai_to_bam now with ability to specify samtools path as well as better error handling and output

diff --git a/bin/sai_to_bam b/bin/sai_to_bam
--- a/bin/sai_to_bam
+++ b/bin/sai_to_bam
@@ -1,21 +1,55 @@
 #!/bin/bash
 
+# Initially set sam_path to default path
+sam_path=$(which samtools)
+
+while getopts ":p:" opt
+do
+    case "$opt" in
+        p)
+            sam_path=$OPTARG
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument." >&2
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND - 1))
+
 ## Convert sai file to indexed bam
 if [ -z $1 ]
 then
-    echo "Please provide an sai file to convert"
+    echo "Please provide an sai file to convert" >&2
     exit 1
 fi
+echo "Using ${sam_path}"
 
-# Filename no extension
+# Filename sans .sai extension
 filename=${1%.sai}
 
 # Convert sai to bam
-samtools view -Sb "${filename}.sai" > "${filename}_unsorted.bam"
+${sam_path} view -Sb "${filename}.sai" > "${filename}_unsorted.bam"
+if [ $? -ne 0 ]
+then
+    echo "Failed to convert ${filename}.sai to unsorted bam" >&2
+    rm ${filename}_unsorted.bam
+    exit $?
+fi
 
 # Sort bam file
-samtools sort "${filename}_unsorted.bam" "${filename}"
+${sam_path} sort "${filename}_unsorted.bam" "${filename}"
+if [ $? -ne 0 ]
+then
+    echo "Failed to sort ${filename}_unsorted.bam" >&2
+    exit $?
+fi
 rm "${filename}_unsorted.bam"
 
 # Index bam file
-samtools index "${filename}.bam"
+${sam_path} index "${filename}.bam"
+if [ $? -ne 0 ]
+then
+    echo "Failed to index ${filename}.bam" >&2
+    exit $?
+fi
